package com.ulms.auth.event;

import com.ulms.auth.model.User;
import com.ulms.events.member.MemberRegisteredEvent;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.util.UUID;

/**
 * Publishes auth-related events to RabbitMQ.
 */
@Component
@RequiredArgsConstructor
@Slf4j
public class AuthEventPublisher {

    private final RabbitTemplate rabbitTemplate;

    @Value("${rabbitmq.exchange.name:library.events}")
    private String exchangeName;

    /**
     * Publish MemberRegisteredEvent when a new user registers.
     * This triggers Member Service to create a member profile and card.
     */
    public void publishMemberRegistered(User user) {
        MemberRegisteredEvent event = new MemberRegisteredEvent(
                UUID.randomUUID().toString(),
                Instant.now(),
                user.getId().toString(),
                null,  // memberId assigned by Member Service
                user.getFirstName(),
                user.getLastName(),
                user.getEmail(),
                "BASIC",  // Default membership type
                null      // Barcode generated by Member Service
        );

        try {
            rabbitTemplate.convertAndSend(exchangeName, "member.registered", event);
            log.info("Published MemberRegisteredEvent for user: {}", user.getEmail());
        } catch (Exception e) {
            log.error("Failed to publish MemberRegisteredEvent for user: {}", user.getEmail(), e);
            // Don't fail registration if event publishing fails
        }
    }
}
